scrape_configs:
  - job_name: 'prometheus-demo'
    scrape_interval: 5s

    static_configs:
      - targets: ['10.0.2.15:4200']
        labels:
          service: 'demo-microservice'
          group: 'production'
rule_files:
- 'alert.rules'